/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deu.cse.blog.View;

import deu.cse.blog.Model.Comment;
import deu.cse.blog.Model.Post;
import deu.cse.blog.Presenter.CommentPresenter;
import deu.cse.blog.Presenter.ViewPresenter;
import deu.cse.blog.Utils.DataParser;
import deu.cse.blog.Utils.JTableSetting;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 조은진
 */
public class CheckPostView extends javax.swing.JFrame {

    private JScrollPane scrollPane = new JScrollPane();
    private Post selectedPost;
    private String userID = UserSession.getSession();
    private String postID;
    private CommentPresenter commentPresenter = new CommentPresenter();
    private ViewPresenter viewPresenter = new ViewPresenter();

    /**
     * Creates new form CheckPostView
     */
    public CheckPostView() {
    }

    public CheckPostView(Post selectedPost) {

        setLocationRelativeTo(null); // 중앙 정렬

        this.selectedPost = selectedPost;
        postID = selectedPost.getPostId();

        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        blogHomeButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        titleContentLabel = new javax.swing.JLabel();
        postScrollPane = new javax.swing.JScrollPane();
        contentLabel = new javax.swing.JLabel();
        buttomPanel = new javax.swing.JPanel();
        commentButton = new javax.swing.JButton();
        writeCommentScrollPane = new javax.swing.JScrollPane();
        commentArea = new javax.swing.JTextArea();
        commentScrollPane = new javax.swing.JScrollPane();
        commentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));

        blogHomeButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        blogHomeButton.setText("블로그 홈");
        blogHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blogHomeButtonMouseClicked(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        titleLabel.setText("제목 : ");

        titleContentLabel.setText(selectedPost.getTitle());
        titleContentLabel.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(blogHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blogHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        postScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        contentLabel.setText(selectedPost.getContent());
        contentLabel.setBackground(new java.awt.Color(255, 255, 255));
        contentLabel.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        contentLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contentLabel.setOpaque(true);
        postScrollPane.setViewportView(contentLabel);

        buttomPanel.setBackground(new java.awt.Color(255, 255, 255));

        commentButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        commentButton.setText("댓글 달기");
        commentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentButtonMouseClicked(evt);
            }
        });

        commentArea.setColumns(20);
        commentArea.setRows(5);
        writeCommentScrollPane.setViewportView(commentArea);

        javax.swing.GroupLayout buttomPanelLayout = new javax.swing.GroupLayout(buttomPanel);
        buttomPanel.setLayout(buttomPanelLayout);
        buttomPanelLayout.setHorizontalGroup(
            buttomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttomPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(writeCommentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(commentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        buttomPanelLayout.setVerticalGroup(
            buttomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttomPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(commentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(writeCommentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        commentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "작성자", "내용"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        commentScrollPane.setViewportView(commentTable);
        commentScrollPane.setBackground(new Color(255, 255, 255, 0));
        commentScrollPane.getViewport().setOpaque(false);
        JTableSetting.tableInit(commentScrollPane, commentTable);
        JTableSetting.tableHeaderInit(commentTable, 900, 40);
        JTableSetting.commentTableSetting(commentTable);
        ArrayList<Comment> commentList = commentPresenter.findByPostId(postID);

        JTableSetting.insertTableRow((DefaultTableModel) commentTable.getModel(), DataParser.commentsToObject(commentList));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(postScrollPane)
                    .addComponent(commentScrollPane, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(postScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(commentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(buttomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // 블로그 홈 버튼 클릭 시
    private void blogHomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blogHomeButtonMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        viewPresenter.moveToMainView(userID);
    }//GEN-LAST:event_blogHomeButtonMouseClicked

    // 댓글 등록하기 버튼 클릭 시
    private void commentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentButtonMouseClicked
        // TODO add your handling code here:
        if (userID.equals("")) {
            JOptionPane.showMessageDialog(getContentPane(), "로그인을 해주세요!");
            setVisible(false);
            dispose();
            viewPresenter.moveToLoginView();
        } else {
            String content = commentArea.getText();
            Boolean result = commentPresenter.register(postID, content, userID);
            if (result) {
                commentArea.setText("");
                JTableSetting.insertTableRow((DefaultTableModel) commentTable.getModel(), new Object[]{
                    userID, content
                });
            }
        }
    }//GEN-LAST:event_commentButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blogHomeButton;
    private javax.swing.JPanel buttomPanel;
    private javax.swing.JTextArea commentArea;
    private javax.swing.JButton commentButton;
    private javax.swing.JScrollPane commentScrollPane;
    private javax.swing.JTable commentTable;
    private javax.swing.JLabel contentLabel;
    private javax.swing.JScrollPane postScrollPane;
    private javax.swing.JLabel titleContentLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JScrollPane writeCommentScrollPane;
    // End of variables declaration//GEN-END:variables
}
