/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deu.cse.blog.View;

import deu.cse.blog.Model.Post;
import deu.cse.blog.Presenter.PostPresenter;
import deu.cse.blog.Utils.DataParser;
import deu.cse.blog.Utils.JTableSetting;
import deu.cse.blog.View.LoginView;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 조은진
 */
public class MainView extends javax.swing.JFrame {

    private JScrollPane scrollPane = new JScrollPane();
    private PostPresenter postPresenter = new PostPresenter();
    private ArrayList<Post> posts;
    String userId = UserSession.getSession();

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        dispose();
        layoutInit();

        setLocationRelativeTo(null); // 중앙 정렬

        logoutButton.setVisible(false);
        logoutButton.setEnabled(false);
        deleteUserButton.setVisible(false);
        deleteUserButton.setEnabled(false);
        myblogButton.setEnabled(false);

        scrollPane.setBackground(new Color(255, 255, 255, 0));
        scrollPane.getViewport().setOpaque(false);
        JTableSetting.tableInit(scrollPane, jTable2);
        JTableSetting.tableHeaderInit(jTable2, 900, 100);
        JTableSetting.postTableSetting(jTable2);

        posts = postPresenter.findAll();
        JTableSetting.insertTableRow((DefaultTableModel) jTable2.getModel(), DataParser.postsToObject(posts));
        setVisible(true);
    }

    public MainView(String userId) {
        initComponents();
        layoutInit();

        setLocationRelativeTo(null); // 중앙 정렬
        loginButton.setVisible(false);
        loginButton.setEnabled(false);
        logoutButton.setEnabled(true);
        logoutButton.setVisible(true);
        deleteUserButton.setVisible(true);
        deleteUserButton.setEnabled(true);
        myblogButton.setEnabled(true);
        useridLabel.setText(userId + "님");

        JTableSetting.tableInit(scrollPane, jTable2);
        JTableSetting.tableHeaderInit(jTable2, 900, 100);
        JTableSetting.postTableSetting(jTable2);
        posts = postPresenter.findAll();
        JTableSetting.insertTableRow((DefaultTableModel) jTable2.getModel(), DataParser.postsToObject(posts));
        setVisible(true);
    }

    public void layoutInit() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        useridLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        postpageButton = new javax.swing.JButton();
        myblogButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        searchBox = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("블로그");
        setSize(new java.awt.Dimension(900, 900));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setMaximumSize(new java.awt.Dimension(900, 150));
        menuPanel.setPreferredSize(new java.awt.Dimension(813, 643));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        useridLabel.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        useridLabel.setText("    ");
        menuPanel.add(useridLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        logoutButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        logoutButton.setText("로그아웃");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        menuPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 150, 50));

        postpageButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        postpageButton.setText("글쓰기");
        postpageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postpageButtonMouseClicked(evt);
            }
        });
        menuPanel.add(postpageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, 50));

        myblogButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        myblogButton.setText("내 블로그");
        myblogButton.setEnabled(false);
        myblogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myblogButtonActionPerformed(evt);
            }
        });
        menuPanel.add(myblogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 50));

        loginButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        loginButton.setText("로그인");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        menuPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 150, 50));

        searchBox.setPreferredSize(new java.awt.Dimension(7, 30));
        menuPanel.add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 60, 310, -1));

        searchButton.setText("🔍");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        menuPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 50, -1));

        deleteUserButton.setText("회원 탈퇴");
        deleteUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserButtonMouseClicked(evt);
            }
        });
        menuPanel.add(deleteUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));
        menuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 120, 20));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "순서", "제목", "작성자", "조회수"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 글쓰기 버튼 클릭 시
    private void postpageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postpageButtonMouseClicked
        // TODO add your handling code here:
        
        if (userId == null) {
            new LoginView();
            setVisible(false);
        } else {
            new PostWriteView();
            setVisible(false);
        }

    }//GEN-LAST:event_postpageButtonMouseClicked
    // 로그인 버튼 클릭 시
    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        new LoginView();
        setVisible(false);
    }//GEN-LAST:event_loginButtonMouseClicked
    // 검색 버튼 클릭 시
    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_searchButtonMouseClicked
    // 로그아웃 버튼 눌렀을 때
    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        new MainView();
        setVisible(false);

    }//GEN-LAST:event_logoutButtonMouseClicked
    // 회원 탈퇴 버튼 클릭 시
    private void deleteUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserButtonMouseClicked
        // TODO add your handling code here:
        new DeleteInfoView();
        setVisible(false);
    }//GEN-LAST:event_deleteUserButtonMouseClicked
    // 글쓰기 버튼 클릭 시
    private void myblogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myblogButtonActionPerformed
        // TODO add your handling code here:
        if(userId!=null){
            new PostWriteView();
            setVisible(false);
        }else{
            new LoginView();
            setVisible(false);
        }
        
    }//GEN-LAST:event_myblogButtonActionPerformed
    // 테이블에 있는 목록 클릭 시
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        Post selectedPost = posts.get(row);

        new CheckPostView(selectedPost);
        setVisible(false);

    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainView().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton myblogButton;
    private javax.swing.JButton postpageButton;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel useridLabel;
    // End of variables declaration//GEN-END:variables
}
