/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.blog.View;

import deu.cse.blog.Model.Post;
import deu.cse.blog.Presenter.Originator;
import deu.cse.blog.Presenter.PostPresenter;
import deu.cse.blog.Utils.ViewManager;
import java.util.TimerTask;
import java.util.Timer;
import javax.swing.JOptionPane;

/**
 *
 * @author 강대한
 */
public class MyPostView extends javax.swing.JFrame {

    private PostPresenter postPresenter = new PostPresenter();
    private Originator originator = new Originator();
    private boolean isUndo;
    private String title;
    private String content;
    private String state;
    private String postID;

    /**
     * Creates new form MyPostView
     */
    public MyPostView() {
        initComponents();
    }

    public MyPostView(Post selectedPost) {
        state = selectedPost.getContent();
        postID = selectedPost.getPostId();
        title = selectedPost.getTitle();
        content = selectedPost.getContent();
        originator.setState(state);
        
        initComponents();
        setLocationRelativeTo(null); // 중앙 정렬
        setVisible(true);
        Timer m = new Timer();
        TimerTask task = new TimerTask() { // 글의 내용이 바뀌어질 때 마다 글 내용 저장
            @Override
            public void run() {
                if (!state.equals(contentArea.getText())) {
                    state = contentArea.getText();
                    originator.setState(state);
                }
            }
        };
        m.schedule(task, 1000, 5000); // 5초 마다 작업 실행
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        myViewButton = new javax.swing.JButton();
        updatePostButton = new javax.swing.JButton();
        deletePostButton = new javax.swing.JButton();
        backwardButton = new javax.swing.JButton();
        forewardButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentArea = new javax.swing.JTextArea();
        titleField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myViewButton.setText("내블로그");
        myViewButton.setAutoscrolls(true);
        myViewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myViewButtonMouseClicked(evt);
            }
        });

        updatePostButton.setText("수정");
        updatePostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePostButtonActionPerformed(evt);
            }
        });

        deletePostButton.setText("삭제");
        deletePostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePostButtonActionPerformed(evt);
            }
        });

        backwardButton.setText("");
        backwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backwardButtonActionPerformed(evt);
            }
        });

        forewardButton.setText("");
        forewardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forewardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(myViewButton)
                .addGap(28, 28, 28)
                .addComponent(backwardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forewardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(updatePostButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletePostButton)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myViewButton)
                    .addComponent(updatePostButton)
                    .addComponent(deletePostButton)
                    .addComponent(backwardButton)
                    .addComponent(forewardButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        contentArea.setColumns(20);
        contentArea.setRows(5);
        contentArea.setText(content);
        jScrollPane1.setViewportView(contentArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        titleField.setText(title);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleField)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePostButtonActionPerformed
        String post = contentArea.getText();
        String title = titleField.getText();
        String name = UserSession.getSession();
        boolean success = postPresenter.update(title, post, name, postID); // 글 수정

        if (success) {
            JOptionPane.showMessageDialog(getContentPane(), "수정 완료!");
            this.setVisible(false);
            dispose();
            ViewManager.moveToMyView();
        }
    }//GEN-LAST:event_updatePostButtonActionPerformed

    private void backwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardButtonActionPerformed
        isUndo = true;
        state = originator.getState(isUndo); // 실행 취소
        contentArea.setText(state);
    }//GEN-LAST:event_backwardButtonActionPerformed

    private void forewardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forewardButtonActionPerformed
        isUndo = false;
        state = originator.getState(isUndo); // 되돌리기
        contentArea.setText(state);
    }//GEN-LAST:event_forewardButtonActionPerformed

    private void deletePostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePostButtonActionPerformed
        boolean success = postPresenter.delete(postID); // 글 삭제

        if (success) {
            JOptionPane.showMessageDialog(getContentPane(), "삭제 완료!");
            this.setVisible(false);
            dispose();
            ViewManager.moveToMyView();
        }
    }//GEN-LAST:event_deletePostButtonActionPerformed

    private void myViewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myViewButtonMouseClicked
        this.setVisible(false);
        dispose();
        ViewManager.moveToMyView();
    }//GEN-LAST:event_myViewButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backwardButton;
    private javax.swing.JTextArea contentArea;
    private javax.swing.JButton deletePostButton;
    private javax.swing.JButton forewardButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton myViewButton;
    private javax.swing.JTextField titleField;
    private javax.swing.JButton updatePostButton;
    // End of variables declaration//GEN-END:variables
}
